apiVersion: v1
kind: Service
metadata:
  namespace: test-1
  labels:
    app: todo-mongodb
  name: todo-mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: todo-mongodb
