apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-app-deploy
  namespace: test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server-app
  template:
    metadata:
      labels:
        app: todo-server-app
    spec:
      containers:
      - image: youngwoochun/custom-docker-images:todo-server-kubernetes-app
        name: container1
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: server-side-configs
        - secretRef:
            name: server-side-secrets
