version: 2.1

references:

base_image: &base_image
  hashicorp/terraform:light

working_directory: &working_directory
  ~/Final-Project

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory

repo_cache_key: &repo_cache_key v1-repo-{{ .Branch }}-{{ .Revision }}

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      terraform init

orbs:
  aws-eks: circleci/aws-eks@1.0.0
  kubernetes: circleci/kubernetes@0.11.1

environment: &environment
  parameters:
    region:
      type: env_var_name
      default: REGION

jobs:
  k8s-deployment:
    <<: *environment
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          Name of AWS region
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/nginx-app-deploy.yaml"
          get-rollout-status: true
          resource-name: deployment/nginxapp
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/nginx-app-service.yaml"
      - run:
          name: checking svc, deploy
          command: |
            kubectl get deployments --all-namespaces
            kubectl get svc --all-namespaces
            kubectl describe svc nginxapp
      - run:
          name: checking svc, deploy
          command: |
            kubectl get svc --all-namespaces
  undeploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: ""
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/delete-resource:
          resource-types: "deployment,service"
          label-selector: "app=nginx-app"
          wait: true
      - run:
          name: Check on pod status
          command: |
            kubectl get pods
  plan:
    <<: *default_config
    steps:
      - checkout
      - *terraform_init
      - *save_repo
      - *restore_repo
      - run:
          name: terraform plan
          command: |
            cd route53
            terraform plan -input=false -var-file=terraform.tfvars
  apply:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          command: |
            terraform apply --auto-approve -var-file=terraform.tfvars
  destroy:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          command: |
            terraform destroy --auto-approve -var-file=terraform.tfvars


workflows:
  version: 2
  kubernetes_deploy:
    jobs:
      - k8s-deployment:
          cluster-name: nginx_app
          aws-region: us-east-1
      - plan:
          requires:
            - k8s-deployment
      - hold-apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold-apply
      - hold-undeploy:
          type: approval
          requires:
            - k8s-deployment
      - undeploy-application:
          cluster-name: nginx_app
          aws-region: us-east-1
          requires:
            - hold-undeploy
      - destroy:
          requires:
            - undeploy-application
