version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.0
  kubernetes: circleci/kubernetes@0.11.1

environment: &environment
  parameters:
    region:
      type: env_var_name
      default: REGION

jobs:
  k8s-deployment:
    <<: *environment
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          Name of AWS region
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/nginx-app-deploy.yaml"
          get-rollout-status: true
          resource-name: deployment/nginxapp
      - kubernetes/create-or-update-resource:
          resource-file-path: "deployment/nginx-app-service.yaml"
      - run:
          name: checking svc, deploy
          command: |
            kubectl get deployments --all-namespaces
            kubectl get svc --all-namespaces
            kuebctl describe svc nginxapp
  undeploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: ""
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/delete-resource:
          resource-types: "deployment,service"
          label-selector: "app=nginx-app"
          wait: true
      - run:
          name: Check on pod status
          command: |
            kubectl get pods

workflows:
  version: 2
  kubernetes_deploy:
    jobs:
      - k8s-deployment:
          cluster-name: nginx_app
          aws-region: us-east-1
      - hold-undeploy:
          type: approval
          requires:
            - k8s-deployment
      - undeploy-application:
          cluster-name: nginx_app
          aws-region: us-east-1
          requires:
            - hold-undeploy
