apiVersion: v1
kind: Service
metadata:
  name: nginxapp
  labels:
    app: nginx-app
spec:
  # automatically create an external load-balanced IP for the service.
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: nginx-app
