apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-app
  name: nginxapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-app
    spec:
      containers:
      - image: youngwoochun/custom-docker-images:nginx-app
        name: app
        ports:
        - containerPort: 8080
